// 1. Data Types
   // --Primitive Data Types
   // --Non-Primitive Data Types


// Primitive data types in JavaScript include:

   // Numbers - Integers, floats
   // Strings - Any data under single quote, double quote or backtick quote
   // Booleans - true or false value
   // Null - empty value or no value
   // Undefined - a declared variable without a value
   // Symbol - A unique value that can be generated by Symbol constructor



// Non-primitive data types in JavaScript includes:

   // Objects
   // Arrays


// 3 Let us compare different data values.

let numOne=3;
let numTwo=3;
console.log(numOne== numTwo)

let js = 'javascript';
let py = 'python';
console.log(js==py)

let lightOn = true;
let lightOff = false;

console.log(lightOn == lightOff)






// 4. Non-Primitive Data Types
   // Non-primitive data types are modifiable or mutable
   

   let nums = [1,2,3];
   nums[0] =10;
   console.log("\n\n\ Modifiable or mutable Value " + nums) 


/* Non-primitive data types cannot be compared by value.

 comparison by location
 all array and object and variable take diffrent 0location

 */


console.log("\n\n\nNo-primitive datatype comparsion")
let numms = [1,2,3];
let number = [1,2,3];

console.log ( numms == number )


let userOne = {
 name:'Abhi',
 role:'Teacher',
 country: 'India'
}

let userTwo = {

   name:'Abhi',
   role: 'Teacher',
   country:'India'
}  



console.log('\n\n\n'+ userOne == userTwo) // false



// Non-primitive values are referred to as reference types, because they are being compared by reference instead of value. 

let Numss = [1,2,3];
let Numbers = nums;

console.log('Compared by reference instead of value')
console.log( Numss == Numbers)


console.log('\n\n Day 2 Exercises')

// Declare a variable named challenge and assign it to an initial value '30 Days Of JavaScript'.

let AssignString = 'Days of javascript';


console.log("using substr= "+ AssignString.substr(0, 1));
console.log("using substring= " + AssignString.substring(1,4));

console.log(AssignString.split());

let ss = 'Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon';
console.log(ss.split(' ').reverse());

let replaceCh = "  30 days of javascript  ";

console.log(replaceCh.replace('javascript', 'python'))
console.log(replaceCh.charAt(14));
console.log(replaceCh.charCodeAt(1));


let searchString = 'You cannot end a sentence with because because because is a conjunction'
console.log(searchString.search('because'))

console.log(replaceCh.trim(''));;

let string = 'Love is the best to in this world'

console.log(string.endsWith('world'));
console.log(string.match('regEx'))

let str1 = '30 days of';
let str2 = 'javascript';

console.log(str1 .concat(' ' +str2));
console.log('\n'+str1.repeat('\n'+2 +'\n'));


// Check if typeof '10' is exactly equal to 10. If not make it exactly equal.

let strs = '10';

let stri = parseInt(strs);
console.log(typeof(stri) + stri);


// Check if parseFloat('9.8') is equal to 10 if not make it exactly equal with 10.


let pFloat = '9.8';
let rFloat = parseFloat(pFloat);
console.log(Math.ceil(rFloat))


let pys = "python";
let jar = "jargon";

// console.log(pys.match('on'));
// console.log(jar.match('on'));

if (pys.includes('on')==jar.includes('on')){

   console.log(" find")

}
else{

console.log("not find")
}

// let ranDom = Math.ranDom();
// let numBtn = ranDom;

// let  

let ranDom = Math.floor( Math.random() * 100);


console.log(ranDom);

let ranDonbt = Math.floor(Math.random () * 51) + 50;

console.log("Random number b/w 50 t0 100 = " + ranDonbt);


let ranNum = Math.random() * 200;


console.log("Random number b/w 0 to 255= " + ranNum)


let nString = "JavaScript";


console.log("nstring= ṬṬ" + Math.random() * nString.length)





